name:                widx
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/widx#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2017 myuon
category:            UI
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  widx:
    source-dirs:      src
    main:             Main.hs
