name:                widx
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/widx#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2017 myuon
category:            Game
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- sdl2
- lens
- containers
- reflection
- extensible
- template-haskell
- mtl
- data-default
- trifecta
- linear
- colors

default-extensions:
- Strict
- StrictData
- DataKinds
- GADTs
- TemplateHaskell
- LambdaCase
- TypeApplications
- TypeOperators
- FlexibleContexts
- Rank2Types
- KindSignatures
- OverloadedLabels
- MultiParamTypeClasses
- FlexibleInstances
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src
  other-modules: Paths_widx

